
//CATEGORY ACTIONS
//export const GET_ITEMS_BY_CATEGORY = 'GET_ITEMS_BY_CATEGORY';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CONNECT_CATEGORIES_START = 'CONNECT_CATEGORIES_START';
export const CLEAN_UP_CATEGORY = 'CLEAN_UP_CATEGORY';

//ITEM ACTIONS
export const GET_ITEM_BY_ID = 'GET_ITEM_BY_ID';
export const CONNECT_CATEGORY_ITEMS_START = 'CONNECT_CATEGORY_ITEMS_START';
export const GET_CATEGORY_ITEMS_SUCCESS = 'GET_CATEGORY_ITEMS_SUCCESS';
export const CLEAN_UP_ITEMS = 'CLEAN_UP_ITEMS';

//AUTH ACTIONS
export const CONNECT_AUTH_START = 'CONNECT_AUTH_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

//RESULTS ACTIONS
export const CONNECT_RESULTS_START = 'CONNECT_RESULTS_START';
export const CREATE_RESULT_SUCCESS = 'CREATE_RESULT_SUCCESS';
export const CREATE_RESULT_ERROR = 'CREATE_RESULT_ERROR';





/* export const CONNECT_AUTH_START = 'CONNECT_AUTH_START';
export const AUTHENTICATE = 'AUTHENTICATE';
export const SET_DID_TRY_AL = 'SET_DID_TRY_AL';
export const LOGOUT = 'LOGOUT';
export const FIREBASE_AUTH_ERROR = 'FIREBASE_AUTH_ERROR';
export const UPDATE_FIREBASE_USER_SUCCESS = 'UPDATE_FIREBASE_USER_SUCCESS';
export const UPDATE_FIREBASE_USER_ERROR = 'UPDATE_FIREBASE_USER_ERROR';
export const CLEAN_UP_AUTH_ERROR = 'CLEAN_UP_AUTH_ERROR'; */

//FORM ACTIONS
export const CONNECT_SIGN_UP_NEW_USER_START = 'CONNECT_SIGN_UP_NEW_USER_START';
export const SIGN_UP_NEW_USER_SUCCESS = 'SIGN_UP_NEW_USER_SUCCESS';
