
//CATEGORY ACTIONS
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CONNECT_CATEGORIES_START = 'CONNECT_CATEGORIES_START';
export const CLEAN_UP_CATEGORY = 'CLEAN_UP_CATEGORY';

//ITEM ACTIONS
export const GET_ITEM_BY_ID = 'GET_ITEM_BY_ID';
export const CONNECT_CATEGORY_ITEMS_START = 'CONNECT_CATEGORY_ITEMS_START';
export const GET_CATEGORY_ITEMS_SUCCESS = 'GET_CATEGORY_ITEMS_SUCCESS';
export const CLEAN_UP_ITEMS = 'CLEAN_UP_ITEMS';

//AUTH ACTIONS
export const CONNECT_AUTH_START = 'CONNECT_AUTH_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

//RESULTS ACTIONS
export const CONNECT_RESULTS_START = 'CONNECT_RESULTS_START';
export const CREATE_RESULT_SUCCESS = 'CREATE_RESULT_SUCCESS';
export const CREATE_RESULT_ERROR = 'CREATE_RESULT_ERROR';

//USER LIST ACTIONS
export const CONNECT_LIST_START = 'CONNECT_LIST_START';
export const CREATE_LIST_SUCCESS = 'CONNECT_LIST_SUCCESS';
export const CREATE_LIST_ERROR = 'CONNECT_LIST_ERROR';
export const GET_LIST_START = 'GET_LIST_START';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_ERROR = 'GET_LIST_ERROR';

