
//CATEGORY ACTIONS
//export const GET_ITEMS_BY_CATEGORY = 'GET_ITEMS_BY_CATEGORY';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CONNECT_CATEGORIES_START = 'CONNECT_CATEGORIES_START';
export const CLEAN_UP_CATEGORY = 'CLEAN_UP_CATEGORY';

//ITEM ACTIONS
export const GET_ITEM_BY_ID = 'GET_ITEM_BY_ID';
export const CONNECT_CATEGORY_ITEMS_START = 'CONNECT_CATEGORY_ITEMS_START';
export const GET_CATEGORY_ITEMS_SUCCESS = 'GET_CATEGORY_ITEMS_SUCCESS';
export const CLEAN_UP_ITEMS = 'CLEAN_UP_ITEMS';